version: "3.8"
services:
  item-service:
    container_name: item-service
    depends_on:
      - item-db
    image: item-service
    build:
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8085:8085"
  item-db:
    container_name: item-db
    restart: always
    image: mongo:7.0.8-rc0-jammy
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - item-db-volume:/var/lib/item-db

volumes:
  item-db-volume: