version: "3.8"

services:
  item-service:
    container_name: item-service
    depends_on:
      item-db:
        condition: "service_healthy"
    image: item-service
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8091:8091"
    networks:
      - wavshare-nw
  item-db:
    container_name: item-db
    image: mongo:7.0.8-rc0-jammy
    restart: unless-stopped
    environment:
      MONGO_PORT: 27021
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    command: ["mongod", "--port", "27021"]
    ports:
      - "27021:27021"
    expose:
      - 27021
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27021/test --quiet
      interval: 10s
      timeout: 15s
      retries: 3
      start_period: 20s
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - item-db-volume:/var/lib/item-db
    networks:
      - wavshare-nw

volumes:
  item-db-volume:

networks:
  wavshare-nw:
    name: wavshare-nw
    external: true