spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
server:
  port: ${SERVER_PORT}
  error:
    include-message: always
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/swagger.html"