spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}
server:
  port: ${SERVER_PORT}
  error:
    include-message: always
springdoc:
  api-docs:
    path: "/docs"
  swagger-ui:
    path: "/swagger.html"