apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: "1"
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 700
      default_user_tags.administrator = true
  service:
    type: LoadBalancer