apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1Gi
      cpu: "1"
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 700
      default_user_tags.administrator = true
  service:
    type: LoadBalancer